groups:
  - name: "main"
    jobs:
      - "build"
      - "e2e"
  - name: "resources"
    jobs:
      - "version-resource"
      
resource_types:
  - name: "version-resource"
    type: docker-image
    source:
      repository: "quay.io/markus/demo-app"
      tag: "version-resource"

resources:
  - name: "git"
    type: git
    check_every: 30s
    source:
      uri: "git@github.com:markuskobler/demo-app.git"
      branch: "master"
      private_key: ((private_key))

  - name: "docker"
    type: docker-image
    source:
      repository: "quay.io/markus/demo-app"
      tag: "latest"
      username: "markus+concourse"
      password: ((docker_password))

  - name: "version-resource"
    type: docker-image
    source:
      repository: "quay.io/markus/demo-app"
      tag: "version-resource"
      username: "markus+concourse"
      password: ((docker_password))

  - name: "version"
    type: version-resource
    check_every: 10s
    source:
      endpoint: http://demo.distinctive.co/version

jobs:
  - name: "build"
    plan:
      - get: demo
        resource: git
        trigger: true
      - task: build
        timeout: 10m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: "quay.io/markus/demo-build"
              tag: "golang-1.10-alpine"

          inputs:
            - { name: "demo", path: go }
          outputs:
            - { name: out }
          params:
            CGO_ENABLED: "0"

          run:
            path: sh
            dir: go
            args:
              - -xc
              - |
                go generate ./src/demo
                go build -o ../out/demo --ldflags "-X main.commit=$(git rev-parse HEAD)" ./src/demo
                cp Dockerfile ../out/
      - put: docker
        params: { build: out }
        get_params: { skip_download: true }

  - name: "e2e"
    plan:
      - aggregate:
        - get: demo
          resource: git
          passed: [ "build" ]
        - get: version
          trigger: true
      - task: test
        timeout: 10m
        file: demo/.ci/e2e.yml

  - name: version-resource
    serial: true
    plan:
      - get: git
      - task: build
        file: git/src/resources/version/.ci/build.yml
      - put: version-resource
        params:
          build: build
          get_params: { skip_download: true }
