resources:
  - name: "git"
    type: git
    source:
      uri: "git@github.com:markuskobler/demo-app.git"
      branch: master
      private_key: ((private_key))

  - name: "docker"
    type: docker-image
    source:
      repository: "quay.io/markus/demo-app"
      username: "markus+concourse"
      password: ((docker_password))

jobs:
  - name: "build"
    plan:
      - get: demo
        resource: git
        trigger: true
      - aggregate:
        - task: build
          timeout: 10m
          file: demo/.ci/build.yml
        - task: test
          timeout: 10m
          file: demo/.ci/test.yml
      - put: docker
        params: { build: out }
        get_params: { skip_download: true }
