resources:
  - name: "demo"
    type: git
    source:
      uri: git@github.com:markuskobler/demo-app.git
      private_key: |
        ((private_key))

jobs:
  - name: "build"
    plan:
      - get: demo
        trigger: true

      - task: build
        timeout: 10m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: "golang:1.10-alpine" }

          inputs: [{ name: "demo", path: go }]

          outputs: [{ name: out }]

          params: { CGO_ENABLED: "0" }

          run:
            path: bash
            dir: go
            args:
              - -exc
              - |
                go generate ./src/demo
                go build -o ../out/demo --ldflags "-X main.commit=$(git rev-parse --short HEAD)" ./src/demo
                cp Dockerfile ../out/
