platform: linux
image_resource:
  type: docker-image
  source: { repository: "quay.io/markus/demo-build", tag: "golang-1.10-alpine" }

inputs:
- name: git
  path: go

outputs:
- name: build

run:
  path: go/src/resources/version/.ci/build.sh
