platform: linux
image_resource:
  type: docker-image
  source: { repository: "quay.io/markus/demo-build", tag: "golang-1.10-alpine" }

inputs:
- { name: "demo", path: go }
outputs:
- { name: out }
params:
  CGO_ENABLED: "0"

run:
  path: sh
  dir: go
  args:
    - -xc
    - |
      go generate ./src/demo
      go build -o ../out/demo --ldflags "-X main.commit=$(git rev-parse --short HEAD)" ./src/demo
      cp Dockerfile ../out/
